# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mKKxL7s6WIJJ-7s3SethVWvP7O3dGMPH
"""

# utils.py
import cv2
import numpy as np
from tensorflow.keras.models import load_model

# 감정 클래스 라벨
emotion_labels = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

# 모델 로드
model = load_model("model/emotion_model.h5")

def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)

    if len(faces) == 0:
        return None, None

    x, y, w, h = faces[0]
    roi_gray = gray[y:y+h, x:x+w]
    roi_gray = cv2.resize(roi_gray, (48, 48))
    roi_gray = roi_gray.astype("float") / 255.0
    roi_gray = np.expand_dims(roi_gray, axis=-1)
    roi_gray = np.expand_dims(roi_gray, axis=0)

    return roi_gray, (x, y, w, h)

def predict_emotion(image):
    processed_img, face_coords = preprocess_image(image)
    if processed_img is None:
        return "얼굴을 감지하지 못했습니다.", None

    prediction = model.predict(processed_img)
    emotion = emotion_labels[np.argmax(prediction)]
    return emotion, face_coords